### ISSUE TITLE
Limit switch doesn't work

### ISSUE THREAD

**Issue by nickwinn** [signalsciences/SigSciApiPy#10]
On master branch

`./SigSci.py --limit 3`

Produces all results and does not limit the output. Tried in combination with `from`, still same outcome.

**Comment by foospidy** [comment]
Thanks for reporting this @nickwinn. I hope to get a fix in soon.

**Comment by foospidy** [comment]
Fixed this in v0.0.9 https://github.com/signalsciences/SigSciApiPy/releases/tag/v0.0.9
