### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by darrow** [signalsciences/SigSciApiPy#11]
Credentials and corp/sites config should be broken into its own file and not committed to versioning so that updates from git are more streamlined -- and secure.

**Comment by foospidy** [comment]
Hi @darrow, thanks for highlighting this, it's a great point. The script does also read config/credentials from environment variables as an alternative to hard coding them in the script itself. But adding support for a config file and depricating the in-script varaibles makes sense.

**Comment by foospidy** [comment]
Finally made this happen. See this release https://github.com/signalsciences/SigSciApiPy/releases/tag/0.1.0
