### ISSUE TITLE
unable to download signal tagging rules

### ISSUE THREAD

**Issue by nevafuse** [signalsciences/SigSciApiPy#17]
I'm trying to download the signals, but only the signal triggers appear to be getting downloaded when using the --custom-alerts argument.  Is there another argument that downloads the signal tagging rules?  

Is there a way to add signal tagging rules assuming there's another argument/api to download them and/or the functionality is added to --custom-alerts?

**Comment by foospidy** [comment]
It sounds like you may want to use the `--request-rules` option. If that doesn't address it, feel free to re-open this issue.
