### ISSUE TITLE
Receiving strange error when file already exists

### ISSUE THREAD

**Issue by nevafuse** [signalsciences/SigSciApiPy#18]
I'm receiving the following error when the file I'm trying to download to already exists.  If I delete that file, it seems to work fine.  Deleting the file is a fine work around but took a while to figure out that was the issue.  Some additional logging might help the next person who has this issue.

./SigSci.py --custom-alerts --file sigsci.json
Error: Extra data: line 1 column 13 (char 12)
Query: https://dashboard.signalsciences.net/api/v0/corps/mycorp/sites/mysite/alerts

./SigSci.py --request-rules --file sigsci.json
Error: Extra data: line 1 column 30 (char 29)
Query: https://dashboard.signalsciences.net/api/v0/corps/mycorp/sites/mysite/requestRules

**Comment by foospidy** [comment]
Sorry for the delay. Thank you for reporting this! I've addressed this in the 0.1.0 release. Added a check if the file exists. It will give a friendly message and exit if the file does already exist.
