### ISSUE TITLE
signal rules download limited to 20

### ISSUE THREAD

**Issue by nevafuse** [signalsciences/SigSciApiPy#19]
When downloading signal rules, only a max of 20 are returned.  I was able to add the limit query param to the get_configuration url in the code to increase the limit.

**Comment by foospidy** [comment]
Thanks for reporting this. I've addressed it in the 0.1.0 release. When retrieving configuration, the `--limit` option is now supported. Also it will default to 100. See code change here https://github.com/signalsciences/SigSciApiPy/commit/5f5f95a624785c41d8ab0879611a123fcf255e08
