### ISSUE TITLE
question: expose signalsciences api as openapi definition

### ISSUE THREAD

**Issue by mayn** [signalsciences/SigSciApiPy#7]
Is there any advantage to this client vs auto-generating?
I'd like to expose signalsciences api via openapi v2 definition and auto generate clients for multiple languages ie python/go/etc.

Is there any objections to this? Any part of the API that you'd prefer not to be defined?
Are you able to provide a dev account that I can use to validate correctness of the definition and resulting clients?

Thanks.!

**Comment by client9** [comment]
Hello @mayn   Sounds interesting.  Could you make this request to support@signalsciences.com so we can understand more your problems or requirements?   We might have have what you are looking for but haven't released it yet.  regards  --nickg   cto/founder
